language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.cache"
before_install:
- npm config set spin false
- npm install -g bower
- bower --version
- npm install phantomjs-prebuilt
- node_modules/phantomjs-prebuilt/bin/phantomjs --version
install:
- npm install
- bower install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: F7EXUAupE/4JLpL39jAWJkRsBpQL4T4tgX5QL/9WjC3k19wdstg1A/RvZDbgc6z20oH+whhNJr5W+u9jEZMljhmeG4TN1VO2D0BLwglpsBqYcjP02WtwU38nwniCCjFTz/7g8s0EVkKVFp3POhI9PF3I8QnGJycjcL1AGBnflJj0Cgl8/s08DoVVetBMIcpuhY/Kxhb4gBMI/l6cTvL513PR30SFP1ILAmYV6Ygc6TgB5t1j6o4eDlA5Py6pZ9htJlvko1bJ4XFoNTqHC4a5UnrI6xXzJrGa1/2ZGvVCcsdX45p/JlZXMCW9pkMvws2PsuB3/0TEzsDzWp5MabLooAGvvHwNu3wC9Htll1XNydDDx56CHF1UEYckFs8AOgVhKN9F/1iXTzWnTe4PswQsji05+I/Xcc4Vz/iI4voYigibOz2EGyfjK9Ev+r4J8w+puTmWtJsKZonklHAs6R+DM+aOtFW9USvTsp6/v94LmeWJWi2QXBw+lNuv1XytB8kiz3FwMVZ3Wa/6R5AZk8ft9qeLeD3UbyJ8AyqDsS6XEUk8UBdFp32uyU1zQz0QPgTtXtxZmMJzeFUyiQppHkiS9nYqaj4m5W3b3KbvLuMFW7/lTLPsjhpD5dfStZuNqc/HOw0WZLUzDDSrVDNsbTenGZHaBhfIsSuH31QHamquqXA=
  app: stormy-temple-98352
  on:
    repo: steveszc/chatter-ui
